export * from './MainView'
export * from './Startpage'
export * from './SearchProperties'
export * from './UserProperties'
export * from './LoginView'
// export * from './MessagesView'
// export * from './PropertyDetailsView'
// export * from './PropertyCategories'
// export * from './PropertyDetails'